apiVersion: v1
kind: Pod
metadata:
  name: snowflake-app
spec:
  containers:
    - name: snowflake-id-generator
      image: snowflake-id-generator:latest
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "500m"
          memory: "256Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /management/health/livenessState
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
